# Generated by Django 3.2.4 on 2021-06-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(choices=[('short', 'Short (>20m)'), ('medium', 'Medium (20m-1h'), ('long', 'Long (<1h)')], default='short', max_length=6),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='Describe your recipe', max_length=100),
        ),
    ]
