# Generated by Django 3.2.4 on 2021-06-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210630_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='Describe your recipe', max_length=75),
        ),
    ]
