# Generated by Django 3.2.5 on 2021-07-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='Describe your recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(choices=[('short', 'Short (<20m)'), ('medium', 'Medium (20m-1h)'), ('long', 'Long (>1h)')], default='short', max_length=6),
        ),
        migrations.AlterField(
            model_name='step',
            name='step',
            field=models.TextField(),
        ),
    ]
