# Generated by Django 3.2.5 on 2021-07-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210715_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Enter the name of this recipe', max_length=100),
        ),
    ]
