# Generated by Django 3.2.5 on 2021-07-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1),
        ),
    ]
